1755553311: Traceback (most recent call last):
  File "<stdin>", line 2058, in <module>
  File "<stdin>", line 1158, in split_msg
AttributeError: 'int' object has no attribute 'get'
1755629169: Traceback (most recent call last):
  File "<stdin>", line 2146, in <module>
  File "umqtt/simple.py", line 213, in check_msg
  File "umqtt/simple.py", line 199, in wait_msg
  File "<stdin>", line 1025, in mqtt_callback
AttributeError: 'bytes' object has no attribute 'payload'
1755629260: Traceback (most recent call last):
  File "<stdin>", line 2146, in <module>
  File "umqtt/simple.py", line 213, in check_msg
  File "umqtt/simple.py", line 199, in wait_msg
  File "<stdin>", line 1025, in mqtt_callback
AttributeError: 'bytes' object has no attribute 'payload'
1755629441: Traceback (most recent call last):
  File "<stdin>", line 2146, in <module>
  File "umqtt/simple.py", line 213, in check_msg
  File "umqtt/simple.py", line 199, in wait_msg
  File "<stdin>", line 1025, in mqtt_callback
AttributeError: 'bytes' object has no attribute 'payload'
1755629711: Traceback (most recent call last):
  File "<stdin>", line 2150, in <module>
  File "umqtt/simple.py", line 213, in check_msg
  File "umqtt/simple.py", line 199, in wait_msg
  File "<stdin>", line 1025, in mqtt_callback
AttributeError: 'bytes' object has no attribute 'payload'
1755639195: Traceback (most recent call last):
  File "<stdin>", line 2222, in <module>
  File "<stdin>", line 1635, in split_msg
AttributeError: 'SensorTPAH' object has no attribute 'doc'
1755640976: Traceback (most recent call last):
  File "<stdin>", line 2261, in <module>
  File "<stdin>", line 1214, in split_msg
AttributeError: 'int' object has no attribute 'get'
1755707901: Traceback (most recent call last):
  File "<stdin>", line 2416, in <module>
  File "<stdin>", line 1817, in redraw
TypeError: 'str' object isn't callable
1755708195: Traceback (most recent call last):
  File "<stdin>", line 2416, in <module>
  File "<stdin>", line 1829, in redraw
KeyError: de
1755722965: Traceback (most recent call last):
  File "<stdin>", line 2567, in <module>
  File "<stdin>", line 2206, in draw
NameError: name 'Publisher_ID' isn't defined
1755724499: Traceback (most recent call last):
  File "<stdin>", line 2571, in <module>
  File "<stdin>", line 1314, in split_msg
TypeError: function takes 3 positional arguments but 4 were given
1755734274: Traceback (most recent call last):
  File "<stdin>", line 2560, in <module>
  File "<stdin>", line 1678, in split_msg
  File "<stdin>", line 1868, in prep_record_for_sd
KeyError: hd
1755734497: Traceback (most recent call last):
  File "<stdin>", line 2560, in <module>
  File "<stdin>", line 1678, in split_msg
  File "<stdin>", line 1870, in prep_record_for_sd
ValueError: unknown format code 'd' for object of type 'str'
1755734966: Traceback (most recent call last):
  File "<stdin>", line 2562, in <module>
  File "<stdin>", line 1678, in split_msg
  File "<stdin>", line 1871, in prep_record_for_sd
ValueError: invalid syntax for integer with base 10
1755736174: Traceback (most recent call last):
  File "<stdin>", line 2573, in <module>
  File "<stdin>", line 1311, in split_msg
TypeError: object of type 'int' has no len()
1755760442: Traceback (most recent call last):
  File "<stdin>", line 2595, in <module>
  File "<stdin>", line 1681, in split_msg
  File "<stdin>", line 1903, in prep_record_for_sd
ValueError: invalid syntax for integer with base 10
1755760684: Traceback (most recent call last):
  File "<stdin>", line 2595, in <module>
  File "<stdin>", line 1681, in split_msg
  File "<stdin>", line 1903, in prep_record_for_sd
ValueError: invalid syntax for integer with base 10
1755761109: Traceback (most recent call last):
  File "<stdin>", line 2600, in <module>
  File "<stdin>", line 1311, in split_msg
TypeError: object of type 'int' has no len()
1755761768: Traceback (most recent call last):
  File "<stdin>", line 2601, in <module>
  File "<stdin>", line 1684, in split_msg
  File "<stdin>", line 1909, in prep_record_for_sd
ValueError: invalid syntax for integer with base 10
1755762179: Traceback (most recent call last):
  File "<stdin>", line 2581, in <module>
  File "<stdin>", line 1664, in split_msg
  File "<stdin>", line 1889, in prep_record_for_sd
ValueError: invalid syntax for integer with base 10
1755785907: Traceback (most recent call last):
  File "<stdin>", line 2740, in <module>
  File "<stdin>", line 2204, in redraw
TypeError: text: string required
1755786061: Traceback (most recent call last):
  File "<stdin>", line 2733, in <module>
  File "<stdin>", line 2197, in redraw
TypeError: text: string required
1755786599: Traceback (most recent call last):
  File "<stdin>", line 2733, in <module>
  File "<stdin>", line 2169, in redraw
TypeError: function expected at most 1 arguments, got 2
1755793401: Traceback (most recent call last):
  File "<stdin>", line 2661, in <module>
  File "<stdin>", line 2087, in redraw
TypeError: function expected at most 1 arguments, got 2
1755793931: Traceback (most recent call last):
  File "<stdin>", line 2661, in <module>
  File "<stdin>", line 2088, in redraw
TypeError: function expected at most 1 arguments, got 2
1755794033: Traceback (most recent call last):
  File "<stdin>", line 2660, in <module>
  File "<stdin>", line 2087, in redraw
TypeError: function expected at most 1 arguments, got 2
1755794168: Traceback (most recent call last):
  File "<stdin>", line 2660, in <module>
  File "<stdin>", line 2087, in redraw
TypeError: function expected at most 1 arguments, got 2
1755794832: Traceback (most recent call last):
  File "<stdin>", line 2660, in <module>
  File "<stdin>", line 2087, in redraw
TypeError: can't convert dict to float
1755795812: Traceback (most recent call last):
  File "<stdin>", line 2672, in <module>
  File "<stdin>", line 2098, in redraw
TypeError: function takes 2 positional arguments but 3 were given
1755801477: Traceback (most recent call last):
  File "<stdin>", line 2679, in <module>
NameError: name 'redraw_done' isn't defined
1755882045: Traceback (most recent call last):
  File "<stdin>", line 2663, in <module>
  File "<stdin>", line 1977, in redraw
KeyError: t
1755887183: Traceback (most recent call last):
  File "<stdin>", line 2712, in <module>
NameError: name 'redraw_done' isn't defined
